[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.3"
hex = "0.4.3"
futures = "0.3.21"
tokio = { version = "1.21.1", features = ["full"]}
tokio-stream = "0.1.10"
